CREATE DATABASE ReCapProject


CREATE TABLE Cars(
	
	ID int NOT NULL IDENTITY(1,1) primary key,
	BRANDID int,
	COLORID int,
	MODELYEAR int,
	DAILYPRICE int,
	INFORMATION varchar(50),

	FOREIGN KEY(BRANDID) REFERENCES Brands(Id),
	FOREIGN KEY(COLORID) REFERENCES Colors(Id)
);

CREATE TABLE [dbo].[Brands](
	
	ID int NOT NULL IDENTITY(1,1) primary key,
	BRANDNAME varchar(50)

);

CREATE TABLE [dbo].[Colors](
	
	ID int NOT NULL IDENTITY(1,1) primary key,
	COLORNAME varchar(50)

);


CREATE TABLE [dbo].[Users]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    	[FIRSTNAME] VARCHAR(50) NOT NULL, 
    	[LASTNAME] VARCHAR(50) NOT NULL, 
    	[EMAIL] VARCHAR(100) NOT NULL, 
    	[PASSWORDHASH] VARBINARY(500) NOT NULL, 
    	[PASSWORDSALT] VARBINARY(500) NOT NULL, 
    	[STATUS] BIT NOT NULL
);


CREATE TABLE [dbo].[OperationClaims]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    	[NAME] VARCHAR(250) NOT NULL
);

CREATE TABLE [dbo].[UserOperationClaims]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    	[USERID] INT NULL, 
    	[OPERATIONCLAIMID] INT NULL
);

CREATE TABLE Customers(
	
	ID int NOT NULL IDENTITY(1,1) primary key,
	USERID int,
	CUSTOMERNAME varchar(50)

);


CREATE TABLE Rentals(
	
	ID int NOT NULL IDENTITY(1,1) primary key,
	BRANDID int,
	CUSTOMERID int,
	RENTALDATE datetime,
	RETURNDATE datetime
	
	FOREIGN KEY(BRANDID) REFERENCES Brands(ID),
	FOREIGN KEY(CUSTOMERID) REFERENCES Colors(ID)
);


CREATE TABLE CarImages(
	
	ID int NOT NULL IDENTITY(1,1) primary key,
	CARID int,
	IMAGEPATH varchar(100),
	HISTORY datetime,

	FOREIGN KEY(CARID) REFERENCES Cars(Id)
);